### ISSUE TITLE
ValueError: multi_class should be either multinomial or ovr, got auto

### ISSUE THREAD

**Issue by colorjam** [HazzaCheng/AutoSpeech#1]
Hi, when I run the code `python run_local_test.py -dataset_dir=./sample_data/DEMO -code_dir=./code_submission`, it shows the following error:

```
multi_class should be either multinomial or ovr, got auto
Traceback (most recent call last):
  File "/userhome/repo/AutoSpeech/ingestion/ingestion.py", line 298, in <module>
    M.train(D.get_train(), remaining_time_budget=timer.remain)
  File "./code_submission/tools.py", line 24, in wrapper
    result = method(*args, **kw)
  File "./code_submission/model.py", line 64, in train
    self.model_manager.fit(train_loop_num=self.train_loop_num)
  File "./code_submission/model_manager.py", line 292, in fit
    self._round_num, **kwargs)
  File "./code_submission/models/logistic_regression.py", line 84, in fit
    self._model.fit(x_train, ohe2cat(y_train))
  File "/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py", line 1222, in fit
    self.dual)
  File "/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py", line 434, in _check_solver_option
    "ovr, got %s" % multi_class)
ValueError: multi_class should be either multinomial or ovr, got auto
```

**Comment by colorjam** [comment]
change the `multi_class=ovr` in `logistic_regression.py`, the error is gone.
